### ISSUE TITLE
Ignore flag 'withPresence'.

### ISSUE THREAD

**Issue by alecxandrys** [pubnub/dart#40]
Good day,
I use next code:
`` pubnub!
          .subscribe(channels: _channelsList.toSet(), withPresence: false) ``

After a while app catch a next message:

![изображение](https://user-images.githubusercontent.com/11788884/110628381-fe450f80-81b3-11eb-8c06-df20fa77d78a.png)
![изображение](https://user-images.githubusercontent.com/11788884/110628596-43694180-81b4-11eb-8df3-97226b53bb45.png)

For some reason i have received message from Presence channel. It's provoke a enormous spam of Envelope in eventHandler.
```
pubnub: 3.1.0
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ^2.0.1
```
